os: linux
dist: focal
language: php

php:
  - 8.0

env:
  jobs:
    - COMPOSER_UPDATE_FLAGS="--no-interaction --no-suggest"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

before_script:
  - travis_retry composer update ${COMPOSER_UPDATE_FLAGS}
  - git config --global user.email "scrutinizer-ci@github.com"
  - git config --global user.name "Scrutinizer-CI"

script:
  - vendor/bin/phpunit
